### ISSUE TITLE
InventorySpam causes crash with forge 1.110

### ISSUE THREAD

**Issue by thedroppedpocket** [gigaherz/InventorySpam#10]
forge 107 worked great and now 110 crashes every time I open a world.

**Comment by thedroppedpocket** [comment]
java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.remapName(Ljava/lang/String;)Ljava/lang/String;
	at gigaherz.inventoryspam.ContainerWrapper.<clinit>(ContainerWrapper.java:23)
	at gigaherz.inventoryspam.ScrollingOverlay.clientTick(ScrollingOverlay.java:276)

**Comment by gigaherz** [comment]
Oh 1.13.2. I was confused as to what version of mc was this about. I'll try to fix asap.
