### ISSUE TITLE
Disabling displaying of item removal doesn't work

### ISSUE THREAD

**Issue by MatthiasMann** [gigaherz/InventorySpam#2]
I'm using InventorySpam-1.10.2-0.0.6.jar and I only want to show picked up items so I configured it like this:

    B:ShowItemAdditions=true
    B:ShowItemRemovals=false

But it still shows both removed and picked up items. 

Looking through the code there doesn't seem to be any filter using showItemRemovals.

Also it would be nice if it was possible to limit these message to only picking up items and not crafting or moving items between chests etc.

**Comment by gigaherz** [comment]
Hmmm the code may have been lost during development (or maybe I never wrote the removals condition, dunno). I'll take a look.

As for only showing pickup, well... the way I detect changes is very plain: I compare the old inventory with the new, and see what changed. It doesn't really work for distinguishing where the items come from.

You would pretty much need a whole new approach for the mod.

**Comment by MatthiasMann** [comment]
For item pickups this could be used: EntityItemPickupEvent - but yeah - it's either this event only or checking the player inventory - both won't work together.

**Comment by gigaherz** [comment]
Is that event even called client-side? Because one of the goals of the mod was to avoid requiring a server-side mod, so that players can use it even in vanilla servers... Anyhow, thought for the future. I'm busy porting my codebases to the experimental 1.12 builds.

**Comment by gigaherz** [comment]
I have just released a new version (v1.0.0), and the configuration bug is fixed, among other things. ;P
