### ISSUE TITLE
(1.11.2) 1.12.0-1.0.0 Invisible crafting bug

### ISSUE THREAD

**Issue by TwitchtvCarbs** [gigaherz/InventorySpam#3]
Having a very strange bug when updating to the latest version of InventorySpam. Something I've actually never seen before!

When you place items in your 2x2 crafting grid they go invisable , as do the items being crafted. You can still however retrive the items.

Went back and tested it again having downgraded to 0.0.7 and the items were showing up now. So I'm not sure what happened in the latest update. (ps the soft limit is a great addition to the mod though!)

**Comment by MJRLegends** [comment]
Yeah im guessing this issue too, please fix @gigaherz :P

**Comment by MJRLegends** [comment]
Yeah im getting this issue too, please fix @gigaherz :P

**Comment by MJRLegends** [comment]
Even on the MC 1.10.2 version this is a issue too

**Comment by gigaherz** [comment]
I'll take a look as soon as I get home from work.

**Comment by MJRLegends** [comment]
Thanks :D

**Comment by gigaherz** [comment]
I have released a fix. It's up on curseforge. Hopefully there isn't any other major issue with it. ;P

**Comment by MJRLegends** [comment]
Thanks :)
