### ISSUE TITLE
V1.0.1 Crashes every-time I try to start a singleplayer world

### ISSUE THREAD

**Issue by agentdouble0** [gigaherz/InventorySpam#4]
As it says everytime I try to start a single player world with this mod MC crashes. (This is a new thing, prev I was using version 0.0.7 and it was working just fine except that the config wasn't working which I dismissed at the time. But recently I figured I should update it and so I did)
Java Ver:  jre 1.8.0_131
InventorySpam Ver: 1.0.1
Forge Ver: 13.20.2386

https://pastebin.com/stVZrLnj

**Comment by TwitchtvCarbs** [comment]
Yup was actually just about to report this as well :) The new update did fix the config and the inventory bug though.

**Comment by gigaherz** [comment]
GAH! The one time I forget to test my changes outside the development environment...! ¬¬ I'll fix as soon as I get home.

**Comment by gigaherz** [comment]
So it turns out the 1.12 version does NOT work on 1.11. I released v1.0.2, including a separate 1.11.2 jar.

**Comment by agentdouble0** [comment]
TY :)
