### ISSUE TITLE
[1.12.2] Soft and Fade Limits Ignored?

### ISSUE THREAD

**Issue by naqaden** [gigaherz/InventorySpam#5]
I've tried setting both SoftLimit and FadeLimit to 1, expecting only the most recent item on-screen. Instead I'm seeing 5-6 at a time. It seems like my limits are ignored or I don't understand how to use them.

**Comment by gigaherz** [comment]
Yep, that stuff doens't seem to work the way I thought it should be working. I'll try to fix that asap.

**Comment by gigaherz** [comment]
I released 1.0.3 last night, it should fix your issue.

**Comment by naqaden** [comment]
That was quick, thank you!
