### ISSUE TITLE
1.13 version of the mod is 32 times larger than in 1.12

### ISSUE THREAD

**Issue by mezz** [gigaherz/InventorySpam#9]
I looked in the jar and found this giant `logo.png` haha 

![logo](https://user-images.githubusercontent.com/916092/54484743-12eea700-4829-11e9-95bd-fa5bd3c3d141.png)

**Comment by gigaherz** [comment]
Yeah I copypasta'd that image into a few 1.13 ports... Need to do an iteration of fixing the initial releases, including make proper sized logo images. XD
